### PR TITLE
Improve usage of singleton configs

### LINKED ISSUE #335: Add API versioning scope (v2)
No serious API can leave without versioning.

We had agreed to use versioning in the headers, defaulting to the most recent one whenever explicitly absent. In the Porto meeting, we've decided to use it in the URL instead, like in:

`/api/v1/...`

### PR DESCRIPTION
**Pull request by jbonnet**
Closes #335

### CODE REVIEW

**Comment by jbonnet** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Pull request closed without merging**
