### PR TITLE
Updated README of the license manager

### PR DESCRIPTION
**Pull request by bsilvr**
Hi, 

I've updated the License Manager README with a detailed usage section. If there is anything else you would like to see added please mention.

Thanks,

Bruno Silva

### CODE REVIEW

**Comment by jbonnet** [comment]
Great!
Thanks!

Best,

**Comment by jbonnet** [comment]
@bsilvr 
Could you please also include information on how to update the DB schema?
Thanks

**Comment by bsilvr** [comment]
@jbonnet 
Isn't that already in the usage? the first command I present in the usage section tells how to upgrade the database to the most recent migrations. If you want I could separate into a different section.
Thanks,

**Comment by jbonnet** [comment]
Sorry, must have read it really quick… :-(

**Pull request merged**
