### PR TITLE
Improves code reuse in API models

### PR DESCRIPTION
**Pull request by jbonnet**

### CODE REVIEW

**Comment by jbonnet** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Pull request merged**
