### PR TITLE
Zip store

### PR DESCRIPTION
**Pull request by tchalas-i2cat**
Possibility to store the zip file directly

### CODE REVIEW

**Comment by jbonnet** [comment]
@tchalas-i2cat Sorry for the time this PR exists w/o having been merged... Can you tell me if there are integration tests covering the feature this PR introduces?

**Comment by tchalas-i2cat** [comment]
Hi @jbonnet. No there are no tests right now. I have tested using a local zip file and passing the url as string but I dont know how to involve the create zip function from a test. Should I follow the pattern used under son-tests/int-gtkpkg-sp-catalogue? Thanks

**Comment by dang03** [comment]
Hi @jbonnet, @tchalas-i2cat, I have added a new integration test for son-packages (which is not active yet) that should work with this code. However, the code is not complete yet:
- son-gtkpkg is not calling the store_zip function, which should be called when the nsds, vnfs, pds are submitted to the catalogue. 
- Storing a son-package (the zip file) in the catalogue will return another uuid for the file, however GK currently does not use it.
- GK allows to GET a package from a package descriptor (with PD uuid), but lacks an API to GET a son-package directly with its uuid.

**Comment by jbonnet** [comment]
Thanks, @dang03,

I know, I haven’t yet accepted the PR, can you do it? And also modify the GK to call the zip_store?

Thanks,

________________________________________________________________
José Bonnet
AlticeLabs.com<http://alticelabs.com>
[cid:B4A60A90-BEB9-4456-862B-BEAC27C6B95D@ptin.corpPT.com]

On 15 Nov 2016, at 14:03, Daniel <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jbonnet<https://github.com/jbonnet>, @tchalas-i2cat<https://github.com/tchalas-i2cat>, I have added a new integration test for son-packages (which is not active yet) that should work with this code. However, the code is not complete yet:

 *   son-gtkpkg is not calling the store_zip function, which should be called when the nsds, vnfs, pds are submitted to the catalogue.
 *   Storing a son-package (the zip file) in the catalogue will return another uuid for the file, however GK currently does not use it.
 *   GK allows to GET a package from a package descriptor (with PD uuid), but lacks an API to GET a son-package directly with its uuid.

**Comment by dang03** [comment]
Sure, we will handle it :)
BR

**Comment by jbonnet** [comment]
Top!
Just let me know if you have any doubt…


________________________________________________________________
José Bonnet
AlticeLabs.com<http://alticelabs.com>
[cid:B4A60A90-BEB9-4456-862B-BEAC27C6B95D@ptin.corpPT.com]

On 16 Nov 2016, at 07:54, Daniel <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, we will handle it :)
BR

**Comment by tchalas-i2cat** [comment]
Thanks guys!

Cheers,
Athanasios

2016-11-16 10:06 GMT+01:00 José Bonnet <notifications@github.com>:

> Top!
> Just let me know if you have any doubt…
>
>
> ________________________________________________________________
> José Bonnet
> AlticeLabs.com<http://alticelabs.com>
> [cid:B4A60A90-BEB9-4456-862B-BEAC27C6B95D@ptin.corpPT.com]
>
> On 16 Nov 2016, at 07:54, Daniel <notifications@github.com<mailto:

**Pull request closed without merging**
