### PR TITLE
Improve code reuse in api models

### PR DESCRIPTION
**Pull request by jbonnet**

### CODE REVIEW

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
retest this please

**Comment by felipevicens** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by felipevicens** [comment]
retest this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Comment by jbonnet** [comment]
test this please

**Comment by felipevicens** [comment]
test this please

**Pull request merged**
